"""add_validator_sync_offset

Revision ID: 01bca204c995
Revises: 2cc3bb428546
Create Date: 2025-06-21 15:09:45.183238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bca204c995'
down_revision: Union[str, None] = '2cc3bb428546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validator_sync_offset',
    sa.Column('hotkey', sa.String(), nullable=False),
    sa.Column('last_registration_time', sa.Float(), nullable=False),
    sa.Column('last_sync_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('hotkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validator_sync_offset')
    # ### end Alembic commands ###
