"""add_unbind_signature

Revision ID: 2cc3bb428546
Revises: 4447eb0806fd
Create Date: 2025-06-21 14:38:05.038491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc3bb428546'
down_revision: Union[str, None] = '4447eb0806fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotkey_worker', sa.Column('unbind_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotkey_worker', 'unbind_signature')
    # ### end Alembic commands ###
