from typing import Literal
from fiber.constants import FINNEY_NETWORK, FINNEY_TEST_NETWORK


FINNEY_NETUID = 16
FINNEY_TEST_NETUID = 368

NETWORK_TO_NETUID = {
    FINNEY_NETWORK: FINNEY_NETUID,
    FINNEY_TEST_NETWORK: FINNEY_TEST_NETUID,
}

SECONDS_IN_BLOCK = 12
